Restore behavior from 3.10 when tracing an exception raised within a with
statement.
